# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Kelvin K Chan
email: kelvin.chan273@gmail.com
description: Healthcare Blogger
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://kelvinkchan.com" # the base hostname & protocol for your site
twitter_username: kelvinkchan
github_username:  chanaml
linkedin_username: kelvin-k-chan
paginate: 5
theme-dark: false #Set to true to change to dark website theme

gems: [jekyll-paginate, kramdown]
# Build settings
markdown: kramdown
